[browser]
gatherUsageStats = false

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[client]
caching = true
displayEnabled = true

[runner]
magicEnabled = true
fastReruns = true

[logger]
level = "info"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"